### ISSUE TITLE
Need improvement

### ISSUE THREAD

**Issue by Vitoshka** [EinBaum/SP_SwingTimer#7]
: Is it possible to only show timer when I'm in close range to the target and hitting him?

https://a.radikal.ru/a42/1804/1d/29066dedbaa6.jpg

thx)

**Comment by EinBaum** [comment]
No, and that would defeat one of the purposes of this timer: If you are duelling another melee you can go out of melee range when your swing timer is > 0 and go back into melee range when the timer is 0. This way you avoid getting hit.
